networks:
  pendezzapizza-test-network:
    driver: bridge

services:
  test-database:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_USER: ${TEST_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${TEST_DATABASE_NAME}
    ports:
      - ${TEST_DATABASE_PORT}
    networks:
      - pendezzapizza-test-network
    healthcheck:                          
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10

  test-redis:
    image: redis:8.4.0-alpine
    networks:
      - pendezzapizza-test-network
    healthcheck:                          
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  test-api:
    image: pendezzapizza-api
    environment:
      SPRING_PROFILES_ACTIVE: test        
      SPRING_DATASOURCE_URL: jdbc:mysql://test-database/${TEST_DATABASE_NAME}?createDatabaseIfNotExists=true&serverTimezone=UTC
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_DATA_REDIS_HOST: test-redis
    env_file:
      - ./pendezzapizza-api/.env.test
    networks:
      - pendezzapizza-test-network
    depends_on:
      test-database:
        condition: service_healthy        
      test-redis:
        condition: service_healthy
    volumes:
      - ${CONTAINER_VOLUME}
    ports :
      - ${API_PORT}

