
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   env_file:
  #     - backend/.env
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:${DATABASE_PORT}/${DATABASE_NAME}
  #     SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
  #   networks:
  #     - backend

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3307:${DATABASE_PORT}"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:


