ALTER TABLE restaurant
ADD COLUMN registration_date     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN update_date  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE restaurant
SET registration_date = CURRENT_TIMESTAMP,
    update_date = CURRENT_TIMESTAMP;

