CREATE TABLE IF NOT EXISTS restaurante (
    id BINARY(16) DEFAULT (UUID_TO_BIN(UUID())) PRIMARY KEY,
    nome VARCHAR(200) NOT NULL ,
    taxa_frete DECIMAL(9,2) NOT NULL,
    data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao DATETIME 
);


