CREATE TABLE IF NOT EXISTS cidade (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    nome VARCHAR(200) NOT NULL,
    estado_id BIGINT
);

ALTER TABLE cidade ADD FOREIGN KEY (estado_id) REFERENCES estado (id) ;


