spring.application.name=pendezzapizza-api
#spring.profiles.active=development
server.port=${API_PORT}

spring.messages.encoding=UTF-8

spring.datasource.url=jdbc:mysql://localhost:3307/${DATABASE_NAME}?createDatabaseIfNotExists=true&serverTimeZone=UTC
spring.datasource.username= ${DATABASE_USERNAME}
spring.datasource.password= ${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.baselineOnMigrate = true

spring.flyway.locations=classpath:db/migration, classpath:db/testdata

logging.level.org.flywaydb.core=DEBUG

spring.jpa.show-sql=true

logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000 

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.resource.add-mappings=false

pendezza-pizza.storage.local.direction.diretorio-fotos= J:\\PendezzasPizza\\pendezzapizza-api\\catalogo

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${API_EMAIL_KEY}

spring.freemarker.settings.locale=pt_BR

spring.mail.properties.mail.smtp.replyto=tester.email.sender@pendezzapizza.com
pendezza-pizza.email.sender=Pendezza Pizza <email.teste.pendezzapizza.tcc@gmail.com>

pendezza-pizza.email.impl = sandbox
#pendezza-pizza.email.impl = mock
#pendezza-pizza.email.impl = smtp
pendezza-pizza.email.sandbox.recipient = email.teste.pendezzapizza.tcc@gmail.com

#Isso comprime respostas com o padro de tamanho de 2 Kb
server.compression.enabled=true

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081
#spring.security.oauth2.resourceserver.opaque-token.introspection-uri=http://localhost:8081/oauth2/introspect
#spring.security.oauth2.resourceserver.opaque-token.client-id=algafood-end
#spring.security.oauth2.resourceserver.opaque-token.client-secret=backend123
