#Server
spring.application.name=pendezzapizza-api
server.port=${API_PORT:8080}
server.compression.enabled=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mandatory-file-encoding=UTF-8
spring.messages.encoding=UTF-8

logging.level.org.springframework.security=DEBUG

#Flyway and Mysql

spring.datasource.url=jdbc:mysql://pendezzapizza-mysql/${DATABASE_NAME}?createDatabaseIfNotExists=true&serverTimeZone=UTC
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.baselineOnMigrate = true

spring.devtools.restart.enabled=false
spring.devtools.restart.additional-exclude=**/*.ser
spring.cache.type=redis


spring.flyway.locations=classpath:db/migration, classpath:db/testdata

logging.level.org.flywaydb=DEBUG
logging.level.db.migration=DEBUG

spring.jpa.show-sql=true

logging.level.org.hibernate.type.descriptor.sql=TRACE

# Pageable config

spring.data.web.pageable.page-parameter=currentPage

#Hikari

spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.idle-timeout=10000 

#Jackson

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.resource.add-mappings=false

#Photos

pendezza-pizza.storage.local.direction.diretorio-fotos=/app/catalogo

#Emails
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${API_EMAIL_KEY}

spring.freemarker.settings.locale=pt_BR

spring.mail.properties.mail.smtp.replyto=${SENDER_EMAIL}
pendezza-pizza.email.sender=Pendezza Pizza <${RECIPIENT_EMAIL}>

pendezza-pizza.email.impl = sandbox
#pendezza-pizza.email.impl = mock
#pendezza-pizza.email.impl = smtp
pendezza-pizza.email.sandbox.recipient = ${RECIPIENT_EMAIL}


#Authentication
pendezzapizza.auth.rsa-key-size = 2048

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:80/oauth2/jwks

pendezzapizza.security.config.url=http://pendezzapizza-api:${API_PORT:8080}/oauth2/jwks
pendezzapizza.security.config.url-issuer=http://localhost:80


pendezzapizza.jwt.keystore.jks-location=${JWT_KEYSTORE_LOCATION}
pendezzapizza.jwt.keystore.password=${JWT_KEYSTORE_PASSWORD}
pendezzapizza.jwt.keystore.keypair-alias=${JWT_KEYSTORE_KEYPAIR_ALIAS}

pendezzapizza.auth.token-url=${TOKEN_URL}
pendezzapizza.auth.authorization-url=${AUTH_URL}
pendezzapizza.auth.client-id=${WEB_CLIENT_ID}
pendezzapizza.auth.client-secret=${WEB_CLIENT_SECRET}
pendezzapizza.auth.redirect-uri=${REDIRECT_URL}
pendezzapizza.frontend.url=${FRONT_END_URL}

#Documentation

springdoc.oAuthFlow.authorizationUrl=http://localhost:80/oauth2/authorize
springdoc.oAuthFlow.tokenUrl=${TOKEN_URL}

springdoc.swagger-ui.oauth.client-id=${DOC_CLIENT_ID}
springdoc.swagger-ui.oauth.client-secret=${DOC_CLIENT_SECRET}

springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true

springdoc.packages-to-scan=com.pendezzapizza.pendezzapizza_api.api
springdoc.paths-to-match=/v1/**