server {
    # Escuta na porta 80 (padrão HTTP)
    listen 80;

    location / {
        proxy_pass http://pendezzapizza-api:8080;
    }
    # Define o bloco de configuração para requisições que começam com /api/
    # location /api/ {
    #     # Reescreve a URL removendo o prefixo '/api' antes de passar para o backend
    #     # Exemplo: uma requisição para '/api/pedidos' vira '/pedidos'
    #     rewrite ^/api/(.*) /$1 break;

    #     # Encaminha a requisição para o serviço da API (container ou host) na porta 8080
    #     proxy_pass http://pendezzapizza-api:8080;

    #     # Repassa os cabeçalhos originais para que a API saiba quem é o cliente real
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }
}